- name: Pull JSON from Apps Script and save
  run: |
    curl -A "Mozilla/5.0" -fsSL "https://script.google.com/macros/s/https://script.google.com/macros/s/AKfycbxLbobFHulTTNDAIZckk1IQwqtqOLGZvyRbb9Fwmyq7DeP8t1CH0lhNtG2xuiXSrBEr/exec" -o assets/citation.json
