name: Update citations (daily 09:00 KST)

on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC = 09:00 KST 매일
  workflow_dispatch:       # 필요할 때 수동 실행 버튼

permissions:
  contents: write          # GITHUB_TOKEN에 푸시 권한 부여

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Fetch Scholar & write JSON
        run: |
          python scripts/update_scholar_11.py

      - name: Commit & push if changed
        run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update all paper citations (auto)"
            git push
          fi
